### ISSUE TITLE
NOTES

### ISSUE THREAD

**Issue by tommygebru** [chuneycu2/ColmarAcademy#7]
_NOTE: Always conduct a peer-review with your peers in Slack, this will improve performance and ability to problem solve!_ 💯

Your project contains little to no errors Cyrus, I went ahead and reviewed your work for best practices and general areas of improvement 😃

**Comment by tommygebru** [comment]
**Minor typos and errors:**

- Review line 44 of your HTML, for a missing closing tag `</p>`


- Review lines 204 and 460 of your CSS, for syntax errors with `background-color` vaues

**Comment by chuneycu2** [comment]
Noted! I will update my code - looks like I was experimenting with colors in the CSS and forgot that hashtag in front of the color keyword there.
